# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Render index
        run: |
          Rscript -e 'rmarkdown::render("index.Rmd")'
          tar -czvf github-pages index.html index_files/

      - name: Upload index pages artifact
        uses: actions/upload-pages-artifact@v1.0.6

      - name: Deploy pages
        uses: actions/deploy-pages@v1.2.3
